import type { Post } from "@/types"

export const mockPosts: Post[] = [
  {
    id: "1",
    content: "Just finished my first suturing session in the OT. Hands were shaking but the resident said it's normal for the first few times. Any tips for staying calm during procedures?",
    isAnonymous: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    author: { id: "u1", name: "Aarav Mehta", profileImage: null },
    likeCount: 24,
    commentCount: 6,
    likedByMe: false,
  },
  {
    id: "2",
    content: "Is it normal to feel completely burnt out during clinical rotations? I love medicine but I haven't slept properly in weeks. Looking for advice from anyone who's been through this.",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    author: null,
    anonymousLabel: "Medical Student, Maulana Azad Medical College",
    likeCount: 142,
    commentCount: 38,
    likedByMe: true,
  },
  {
    id: "3",
    content: "Had a patient today thank me for explaining their diagnosis in a way they could actually understand. Small moments like these are why I chose this field.",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    author: null,
    anonymousLabel: "Resident Doctor, AIIMS Delhi",
    likeCount: 89,
    commentCount: 12,
    likedByMe: false,
  },
  {
    id: "4",
    content: "Just finished my first suturing session in the OT. Hands were shaking but the resident said it's normal for the first few times. Any tips for staying calm during procedures?",
    isAnonymous: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    author: { id: "u1", name: "Aarav Mehta", profileImage: null },
    likeCount: 24,
    commentCount: 6,
    likedByMe: false,
  },
  {
    id: "5",
    content: "Is it normal to feel completely burnt out during clinical rotations? I love medicine but I haven't slept properly in weeks. Looking for advice from anyone who's been through this.",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    author: null,
    anonymousLabel: "Medical Student, Maulana Azad Medical College",
    likeCount: 142,
    commentCount: 38,
    likedByMe: true,
  },
  {
    id: "6",
    content: "Had a patient today thank me for explaining their diagnosis in a way they could actually understand. Small moments like these are why I chose this field.",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    author: null,
    anonymousLabel: "Resident Doctor, AIIMS Delhi",
    likeCount: 89,
    commentCount: 12,
    likedByMe: false,
  },
  {
    id: "7",
    content: "Just finished my first suturing session in the OT. Hands were shaking but the resident said it's normal for the first few times. Any tips for staying calm during procedures?",
    isAnonymous: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    author: { id: "u1", name: "Aarav Mehta", profileImage: null },
    likeCount: 24,
    commentCount: 6,
    likedByMe: false,
  },
  {
    id: "8",
    content: "Is it normal to feel completely burnt out during clinical rotations? I love medicine but I haven't slept properly in weeks. Looking for advice from anyone who's been through this.",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    author: null,
    anonymousLabel: "Medical Student, Maulana Azad Medical College",
    likeCount: 142,
    commentCount: 38,
    likedByMe: true,
  },
  {
    id: "9",
    content: "Had a patient today thank me for explaining their diagnosis in a way they could actually understand. Small moments like these are why I chose this field.",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    author: null,
    anonymousLabel: "Resident Doctor, AIIMS Delhi",
    likeCount: 89,
    commentCount: 12,
    likedByMe: false,
  },
]